language: python
python:
  - "2.7"
install:
  - "deactivate"
  - "pip install virtualenv --user"
  - "python validator/deploy/bootstrap.py"
  - ln -s local_settings.py.travis validator/django/website/local_settings.py 
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
  - mysql -e 'CREATE DATABASE travis CHARACTER SET utf8;'
# command to run tests, e.g. python setup.py test
script:
    - "python validator/deploy/tasks.py run_tests:--nologcapture,--with-coverage,-v1 -v"
after_success:
  - cd validator/django/website
  - source .ve/bin/activate
  - coveralls